Added parser for Nback and GNGo
TIGRLab/datman pull request #286
Opened 2020-09-24 16:51 UTC by ThomasHMAC

2020-09-24 16:51 UTC, pep8speaks commented
Hello @ThomasHMAC, thank you for submitting the Pull Request!

* In the file [`bin/dm_parse_GNGo.py`](https://github.com/TIGRLab/datman/blob/805a659b577ee19ce3e54b5ff60759cd01d9bad2/bin/dm_parse_GNGo.py):

> [Line 25:1](https://github.com/TIGRLab/datman/blob/805a659b577ee19ce3e54b5ff60759cd01d9bad2/bin/dm_parse_GNGo.py#L25): [F401](https://duckduckgo.com/?q=pep8%20F401) 'codecs' imported but unused
> [Line 27:1](https://github.com/TIGRLab/datman/blob/805a659b577ee19ce3e54b5ff60759cd01d9bad2/bin/dm_parse_GNGo.py#L27): [F401](https://duckduckgo.com/?q=pep8%20F401) 'pdb' imported but unused
> [Line 29:1](https://github.com/TIGRLab/datman/blob/805a659b577ee19ce3e54b5ff60759cd01d9bad2/bin/dm_parse_GNGo.py#L29): [F401](https://duckduckgo.com/?q=pep8%20F401) 'numpy as np' imported but unused
> [Line 30:1](https://github.com/TIGRLab/datman/blob/805a659b577ee19ce3e54b5ff60759cd01d9bad2/bin/dm_parse_GNGo.py#L30): [F401](https://duckduckgo.com/?q=pep8%20F401) 'os' imported but unused
> [Line 32:1](https://github.com/TIGRLab/datman/blob/805a659b577ee19ce3e54b5ff60759cd01d9bad2/bin/dm_parse_GNGo.py#L32): [F401](https://duckduckgo.com/?q=pep8%20F401) 'subprocess' imported but unused
> [Line 33:1](https://github.com/TIGRLab/datman/blob/805a659b577ee19ce3e54b5ff60759cd01d9bad2/bin/dm_parse_GNGo.py#L33): [F401](https://duckduckgo.com/?q=pep8%20F401) 'glob' imported but unused
> [Line 34:1](https://github.com/TIGRLab/datman/blob/805a659b577ee19ce3e54b5ff60759cd01d9bad2/bin/dm_parse_GNGo.py#L34): [F811](https://duckduckgo.com/?q=pep8%20F811) redefinition of unused 'sys' from line 26
> [Line 34:1](https://github.com/TIGRLab/datman/blob/805a659b577ee19ce3e54b5ff60759cd01d9bad2/bin/dm_parse_GNGo.py#L34): [F401](https://duckduckgo.com/?q=pep8%20F401) 'sys' imported but unused
> [Line 36:10](https://github.com/TIGRLab/datman/blob/805a659b577ee19ce3e54b5ff60759cd01d9bad2/bin/dm_parse_GNGo.py#L36): [E221](https://duckduckgo.com/?q=pep8%20E221) multiple spaces before operator
> [Line 37:10](https://github.com/TIGRLab/datman/blob/805a659b577ee19ce3e54b5ff60759cd01d9bad2/bin/dm_parse_GNGo.py#L37): [E221](https://duckduckgo.com/?q=pep8%20E221) multiple spaces before operator
> [Line 38:12](https://github.com/TIGRLab/datman/blob/805a659b577ee19ce3e54b5ff60759cd01d9bad2/bin/dm_parse_GNGo.py#L38): [E221](https://duckduckgo.com/?q=pep8%20E221) multiple spaces before operator
> [Line 39:6](https://github.com/TIGRLab/datman/blob/805a659b577ee19ce3e54b5ff60759cd01d9bad2/bin/dm_parse_GNGo.py#L39): [E221](https://duckduckgo.com/?q=pep8%20E221) multiple spaces before operator
> [Line 40:7](https://github.com/TIGRLab/datman/blob/805a659b577ee19ce3e54b5ff60759cd01d9bad2/bin/dm_parse_GNGo.py#L40): [E221](https://duckduckgo.com/?q=pep8%20E221) multiple spaces before operator
> [Line 42:10](https://github.com/TIGRLab/datman/blob/805a659b577ee19ce3e54b5ff60759cd01d9bad2/bin/dm_parse_GNGo.py#L42): [E701](https://duckduckgo.com/?q=pep8%20E701) multiple statements on one line (colon)
> [Line 44:1](https://github.com/TIGRLab/datman/blob/805a659b577ee19ce3e54b5ff60759cd01d9bad2/bin/dm_parse_GNGo.py#L44): [E266](https://duckduckgo.com/?q=pep8%20E266) too many leading '#' for block comment
> [Line 46:9](https://github.com/TIGRLab/datman/blob/805a659b577ee19ce3e54b5ff60759cd01d9bad2/bin/dm_parse_GNGo.py#L46): [E701](https://duckduckgo.com/?q=pep8%20E701) multiple statements on one line (colon)
> [Line 50:17](https://github.com/TIGRLab/datman/blob/805a659b577ee19ce3e54b5ff60759cd01d9bad2/bin/dm_parse_GNGo.py#L50): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 51:1](https://github.com/TIGRLab/datman/blob/805a659b577ee19ce3e54b5ff60759cd01d9bad2/bin/dm_parse_GNGo.py#L51): [E722](https://duckduckgo.com/?q=pep8%20E722) do not use bare 'except'
> [Line 55:1](https://github.com/TIGRLab/datman/blob/805a659b577ee19ce3e54b5ff60759cd01d9bad2/bin/dm_parse_GNGo.py#L55): [E266](https://duckduckgo.com/?q=pep8%20E266) too many leading '#' for block comment
> [Line 56:35](https://github.com/TIGRLab/datman/blob/805a659b577ee19ce3e54b5ff60759cd01d9bad2/bin/dm_parse_GNGo.py#L56): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 57:35](https://github.com/TIGRLab/datman/blob/805a659b577ee19ce3e54b5ff60759cd01d9bad2/bin/dm_parse_GNGo.py#L57): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 58:1](https://github.com/TIGRLab/datman/blob/805a659b577ee19ce3e54b5ff60759cd01d9bad2/bin/dm_parse_GNGo.py#L58): [E266](https://duckduckgo.com/?q=pep8%20E266) too many leading '#' for block comment
> [Line 59:1](https://github.com/TIGRLab/datman/blob/805a659b577ee19ce3e54b5ff60759cd01d9bad2/bin/dm_parse_GNGo.py#L59): [E266](https://duckduckgo.com/?q=pep8%20E266) too many leading '#' for block comment
> [Line 62:1](https://github.com/TIGRLab/datman/blob/805a659b577ee19ce3e54b5ff60759cd01d9bad2/bin/dm_parse_GNGo.py#L62): [E265](https://duckduckgo.com/?q=pep8%20E265) block comment should start with '# '
> [Line 65:1](https://github.com/TIGRLab/datman/blob/805a659b577ee19ce3e54b5ff60759cd01d9bad2/bin/dm_parse_GNGo.py#L65): [E266](https://duckduckgo.com/?q=pep8%20E266) too many leading '#' for block comment
> [Line 68:81](https://github.com/TIGRLab/datman/blob/805a659b577ee19ce3e54b5ff60759cd01d9bad2/bin/dm_parse_GNGo.py#L68): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (89 > 80 characters)
> [Line 77:55](https://github.com/TIGRLab/datman/blob/805a659b577ee19ce3e54b5ff60759cd01d9bad2/bin/dm_parse_GNGo.py#L77): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 78:81](https://github.com/TIGRLab/datman/blob/805a659b577ee19ce3e54b5ff60759cd01d9bad2/bin/dm_parse_GNGo.py#L78): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (85 > 80 characters)
> [Line 79:58](https://github.com/TIGRLab/datman/blob/805a659b577ee19ce3e54b5ff60759cd01d9bad2/bin/dm_parse_GNGo.py#L79): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 81:61](https://github.com/TIGRLab/datman/blob/805a659b577ee19ce3e54b5ff60759cd01d9bad2/bin/dm_parse_GNGo.py#L81): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 83:61](https://github.com/TIGRLab/datman/blob/805a659b577ee19ce3e54b5ff60759cd01d9bad2/bin/dm_parse_GNGo.py#L83): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 85:54](https://github.com/TIGRLab/datman/blob/805a659b577ee19ce3e54b5ff60759cd01d9bad2/bin/dm_parse_GNGo.py#L85): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 86:5](https://github.com/TIGRLab/datman/blob/805a659b577ee19ce3e54b5ff60759cd01d9bad2/bin/dm_parse_GNGo.py#L86): [E265](https://duckduckgo.com/?q=pep8%20E265) block comment should start with '# '
> [Line 87:25](https://github.com/TIGRLab/datman/blob/805a659b577ee19ce3e54b5ff60759cd01d9bad2/bin/dm_parse_GNGo.py#L87): [E701](https://duckduckgo.com/?q=pep8%20E701) multiple statements on one line (colon)
> [Line 87:25](https://github.com/TIGRLab/datman/blob/805a659b577ee19ce3e54b5ff60759cd01d9bad2/bin/dm_parse_GNGo.py#L87): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ':'
> [Line 90:5](https://github.com/TIGRLab/datman/blob/805a659b577ee19ce3e54b5ff60759cd01d9bad2/bin/dm_parse_GNGo.py#L90): [E265](https://duckduckgo.com/?q=pep8%20E265) block comment should start with '# '
> [Line 91:19](https://github.com/TIGRLab/datman/blob/805a659b577ee19ce3e54b5ff60759cd01d9bad2/bin/dm_parse_GNGo.py#L91): [E261](https://duckduckgo.com/?q=pep8%20E261) at least two spaces before inline comment
> [Line 91:19](https://github.com/TIGRLab/datman/blob/805a659b577ee19ce3e54b5ff60759cd01d9bad2/bin/dm_parse_GNGo.py#L91): [E262](https://duckduckgo.com/?q=pep8%20E262) inline comment should start with '# '
> [Line 99:5](https://github.com/TIGRLab/datman/blob/805a659b577ee19ce3e54b5ff60759cd01d9bad2/bin/dm_parse_GNGo.py#L99): [E265](https://duckduckgo.com/?q=pep8%2 [...]

2020-09-28 19:06 UTC, jerdra commented on bin/dm_parse_GNGo.py
> +DRYRUN          = arguments['--dry-run']
can you run a linter/code formatter for this? Dawn and I have been using "yapf" to re-format our code!

2020-09-28 19:12 UTC, jerdra commented on bin/dm_parse_GNGo.py
> +if DEBUG : print(arguments)
can you indent here? running a re-formatter could work as well

2020-09-28 19:12 UTC, jerdra commented on bin/dm_parse_GNGo.py
> +if DEBUG: print("\n file: {}".format(inputfile))
same as above re:indenting

2020-09-28 19:24 UTC, jerdra requested changes
Thanks for setting this up Thomas! Just a few stylistic comments I've added. Would recommend that you try a linter/code formatter like yapf to adjust the code style to match what we've set out as code style standards.

Other thing to consider maybe is whether we can refactor these scripts into a single script/library of scripts to handle task parsing since there're a ton of overlaps b/w the two scripts. Obv having something working for the moment is important - but something to think about for sure!

2020-09-28 19:24 UTC, jerdra commented on bin/dm_parse_GNGo.py
> +import sys
Might be a good idea to use "import logging" to print to stdout. Would be worth checking other datman/bin scripts and seeing how they log!

2020-09-28 19:24 UTC, jerdra commented on bin/dm_parse_GNGo.py
> +    if (TrialType == ''):continue
indent here

2020-09-28 19:24 UTC, jerdra commented on bin/dm_parse_Nback.py
> +    TrailTime = int()
```suggestion
    TrialType = str()
    TrialTime = int()
```

2020-09-28 19:24 UTC, jerdra commented on bin/dm_parse_Nback.py
> +            TrailType = line.split(':')[1].replace(" ",'')
```suggestion
            TrialType = line.split(':')[1].replace(" ",'')
```

2020-09-28 19:24 UTC, jerdra commented on bin/dm_parse_Nback.py
> +            TrailTime = line.split(':')[1].replace(" ",'')
```suggestion
            TrialTime = line.split(':')[1].replace(" ",'')
```

2020-09-28 19:24 UTC, jerdra commented on bin/dm_parse_Nback.py
> +    if (TrailType == 'List1') or (TrailType == ''):continue
```suggestion
    if (TrialType == 'List1') or (TrialType == ''):continue
```

Indent would be needed here as well

2020-09-28 19:24 UTC, jerdra commented on bin/dm_parse_Nback.py
> +if DEBUG : print(arguments)
indent here

2020-09-28 19:24 UTC, jerdra commented on bin/dm_parse_Nback.py
> +    trial_dict = {'onset' : TrailTime, 'duration' : 0,
```suggestion
    trial_dict = {'onset' : TrialTime, 'duration' : 0,
```

2020-09-28 19:24 UTC, jerdra commented on bin/dm_parse_Nback.py
> +                 'trial_type' : TrailType, 'correct_response' : corr[str(CorrectResponse)],
```suggestion
                 'trial_type' : TrialType, 'correct_response' : corr[str(CorrectResponse)],
```

2020-09-29 20:01 UTC, ThomasHMAC commented
> Thanks for setting this up Thomas! Just a few stylistic comments I've added. Would recommend that you try a linter/code formatter like yapf to adjust the code style to match what we've set out as code style standards.
> 
> Other thing to consider maybe is whether we can refactor these scripts into a single script/library of scripts to handle task parsing since there're a ton of overlaps b/w the two scripts. Obv having something working for the moment is important - but something to think about for sure!

Thanks for the suggestion Jer, and yes there are tons of overlapping between two scripts. I will try to make a single script/ library of scripts later

2020-09-29 21:54 UTC, DESm1th commented on bin/dm_parse_GNGo.py
> +except myfile.DoesNotExist:
This should be updated to 

```
except FileNotFoundError:
```

2020-09-29 22:10 UTC, DESm1th requested changes
Looks really good, thank you Thomas! Like Jer I just have a few stylistic python-nitpicks, but I'm comfortable approving things as they are now once the exception is fixed. 

1. In python it's good to use snake-case for multi-word variable and function names so for instance "inputfile" would be "input_file" instead. This is a PEP8 practice, but most linters can't check for it.

2. It's a good idea to put code inside a main function / other functions (and then call the main function at the bottom). Every instruction that's not inside of a function gets executed when the script is imported, which can make it difficult or impossible to write tests for code. If it's in a function, though, it doesn't execute until the function is called (with a standard 'guard' at the bottom of the script like below, the main function will always be called if the script is being run directly on the command line and not if it's imported somewhere else)
```
def main():
    # your code here

if __name__ == "__main__":
    main()
```

2020-10-01 13:45 UTC, jerdra requested changes

2020-10-01 13:45 UTC, jerdra commented on bin/dm_parse_GNGo.py
> +    quit()
exception should be fixed here as well FileNotFoundError

2020-10-01 16:13 UTC, DESm1th approved these changes
Thanks Thomas! Good work :D

2020-10-01 16:39 UTC, jerdra approved these changes

2020-10-01 18:59 UTC, merged