[FIX] Make the ea parser work without hardcoded stuff
TIGRLab/datman pull request #292
Opened 2020-11-27 21:38 UTC by DESm1th

This contains my and Thomas' updates and fixes a few bugs that were present.

2020-11-27 21:38 UTC, pep8speaks commented
Hello @DESm1th, thank you for submitting the Pull Request!

* In the file [`bin/dm_parse_ea.py`](https://github.com/TIGRLab/datman/blob/684b033ac4cbfdaa3c57a93c2ac44e235cd898da/bin/dm_parse_ea.py):

> [Line 63:5](https://github.com/TIGRLab/datman/blob/684b033ac4cbfdaa3c57a93c2ac44e235cd898da/bin/dm_parse_ea.py#L63): [E265](https://duckduckgo.com/?q=pep8%20E265) block comment should start with '# '
> [Line 104:5](https://github.com/TIGRLab/datman/blob/684b033ac4cbfdaa3c57a93c2ac44e235cd898da/bin/dm_parse_ea.py#L104): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (2)
> [Line 104:5](https://github.com/TIGRLab/datman/blob/684b033ac4cbfdaa3c57a93c2ac44e235cd898da/bin/dm_parse_ea.py#L104): [E265](https://duckduckgo.com/?q=pep8%20E265) block comment should start with '# '
> [Line 108:27](https://github.com/TIGRLab/datman/blob/684b033ac4cbfdaa3c57a93c2ac44e235cd898da/bin/dm_parse_ea.py#L108): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 109:32](https://github.com/TIGRLab/datman/blob/684b033ac4cbfdaa3c57a93c2ac44e235cd898da/bin/dm_parse_ea.py#L109): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 109:58](https://github.com/TIGRLab/datman/blob/684b033ac4cbfdaa3c57a93c2ac44e235cd898da/bin/dm_parse_ea.py#L109): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 110:54](https://github.com/TIGRLab/datman/blob/684b033ac4cbfdaa3c57a93c2ac44e235cd898da/bin/dm_parse_ea.py#L110): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 110:81](https://github.com/TIGRLab/datman/blob/684b033ac4cbfdaa3c57a93c2ac44e235cd898da/bin/dm_parse_ea.py#L110): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (128 > 80 characters)
> [Line 110:91](https://github.com/TIGRLab/datman/blob/684b033ac4cbfdaa3c57a93c2ac44e235cd898da/bin/dm_parse_ea.py#L110): [E712](https://duckduckgo.com/?q=pep8%20E712) comparison to True should be 'if cond is True:' or 'if cond:'
> [Line 110:91](https://github.com/TIGRLab/datman/blob/684b033ac4cbfdaa3c57a93c2ac44e235cd898da/bin/dm_parse_ea.py#L110): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 113:5](https://github.com/TIGRLab/datman/blob/684b033ac4cbfdaa3c57a93c2ac44e235cd898da/bin/dm_parse_ea.py#L113): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (2)
> [Line 115:21](https://github.com/TIGRLab/datman/blob/684b033ac4cbfdaa3c57a93c2ac44e235cd898da/bin/dm_parse_ea.py#L115): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 117:5](https://github.com/TIGRLab/datman/blob/684b033ac4cbfdaa3c57a93c2ac44e235cd898da/bin/dm_parse_ea.py#L117): [F841](https://duckduckgo.com/?q=pep8%20F841) local variable 'onsets' is assigned to but never used
> [Line 117:11](https://github.com/TIGRLab/datman/blob/684b033ac4cbfdaa3c57a93c2ac44e235cd898da/bin/dm_parse_ea.py#L117): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 119:15](https://github.com/TIGRLab/datman/blob/684b033ac4cbfdaa3c57a93c2ac44e235cd898da/bin/dm_parse_ea.py#L119): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 119:66](https://github.com/TIGRLab/datman/blob/684b033ac4cbfdaa3c57a93c2ac44e235cd898da/bin/dm_parse_ea.py#L119): [E226](https://duckduckgo.com/?q=pep8%20E226) missing whitespace around arithmetic operator
> [Line 121:12](https://github.com/TIGRLab/datman/blob/684b033ac4cbfdaa3c57a93c2ac44e235cd898da/bin/dm_parse_ea.py#L121): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 121:21](https://github.com/TIGRLab/datman/blob/684b033ac4cbfdaa3c57a93c2ac44e235cd898da/bin/dm_parse_ea.py#L121): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ':'
> [Line 122:17](https://github.com/TIGRLab/datman/blob/684b033ac4cbfdaa3c57a93c2ac44e235cd898da/bin/dm_parse_ea.py#L122): [E127](https://duckduckgo.com/?q=pep8%20E127) continuation line over-indented for visual indent
> [Line 122:34](https://github.com/TIGRLab/datman/blob/684b033ac4cbfdaa3c57a93c2ac44e235cd898da/bin/dm_parse_ea.py#L122): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ':'
> [Line 123:29](https://github.com/TIGRLab/datman/blob/684b033ac4cbfdaa3c57a93c2ac44e235cd898da/bin/dm_parse_ea.py#L123): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ':'
> [Line 124:27](https://github.com/TIGRLab/datman/blob/684b033ac4cbfdaa3c57a93c2ac44e235cd898da/bin/dm_parse_ea.py#L124): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ':'
> [Line 125:36](https://github.com/TIGRLab/datman/blob/684b033ac4cbfdaa3c57a93c2ac44e235cd898da/bin/dm_parse_ea.py#L125): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ':'
> [Line 127:11](https://github.com/TIGRLab/datman/blob/684b033ac4cbfdaa3c57a93c2ac44e235cd898da/bin/dm_parse_ea.py#L127): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 127:33](https://github.com/TIGRLab/datman/blob/684b033ac4cbfdaa3c57a93c2ac44e235cd898da/bin/dm_parse_ea.py#L127): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 131:21](https://github.com/TIGRLab/datman/blob/684b033ac4cbfdaa3c57a93c2ac44e235cd898da/bin/dm_parse_ea.py#L131): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 133:30](https://github.com/TIGRLab/datman/blob/684b033ac4cbfdaa3c57a93c2ac44e235cd898da/bin/dm_parse_ea.py#L133): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 133:56](https://github.com/TIGRLab/datman/blob/684b033ac4cbfdaa3c57a93c2ac44e235cd898da/bin/dm_parse_ea.py#L133): [E226](https://duckduckgo.com/?q=pep8%20E226) missing whitespace around arithmetic operator
> [Line 133:81](https://github.com/TIGRLab/datman/blob/684b033ac4cbfdaa3c57a93c2ac44e235cd898da/bin/dm_parse_ea.py#L133): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (90 > 80 characters)
> [Line 133:83](https://github.com/TIGRLab/datman/blob/684b033ac4cbfdaa3c57a93c2ac44e235cd898da/bin/dm_parse_ea.py#L133): [E712](https://duckduckgo.com/?q=pep8%20E712) comparison to False should be 'if cond is False:' or 'if not cond:'
> [Line 133:83](https://github.com/TIGRLab/datman/blob/684b033ac4cbfdaa3c57a93c2ac44e235cd898da/bin/dm_parse_ea.py#L133): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 141:54](https://github.com/TIGRLab/datman/blob/684b033ac4cbfdaa3c57a93c2ac44e235cd898da/bin/dm_parse_ea.py#L141): [E226](https://duckduckgo.com/?q=pep8%20E226) missing whitespace around arithmetic operator
> [Line 141:58](https://github.com/TIGRLab/datman/blob/684b033ac4cbfdaa3c57a93c2ac44e235cd898da/bin/dm_parse_ea.py#L141): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 141:81](https://github.com/TIGRLab/datman/blob/684b033ac4cbfdaa3c57a93c2ac44e235cd898da/bin/dm_parse_ea.py#L141): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (129 > 80 characters)
> [Line 141:88](https://github.com/TIGRLab/datman/blob/684b033ac4cbfdaa3c57a93c2ac44e235cd898da/bin/dm_parse_ea.py#L141): [E226](https://duckduckgo.com/?q=pep8%20E226) missing whitespace around arithmetic operator
> [Line 141:126](https://github.com/TIGRLab/datman/blob/684b033ac4cbfdaa3c57a93c2ac44e235cd898da/bin/dm_parse_ea.py#L141): [E226](https://duckduckgo.com/?q=pep8%20E226) missing whitespace around arithmetic operator
> [Line 144:5](https://github.com/TIGRLab/datman/blob/684b033ac4cbfdaa3c57a93c2ac44e235cd898da/bin/dm_parse_ea.py#L144): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (2)
> [Line 144:5](https://github.com/TIGRLab/datman/blob/684b033ac4cbfdaa3c57a93c2ac44e235cd898da/bin/dm_parse_ea.py#L144): [E265](https://duckduckgo.com/?q=pep8%20E265) block comment should start with '# '
> [L [...]

2020-12-08 21:02 UTC, jerdra submitted a review, later dismissed

2021-01-06 17:05 UTC, josephmje commented
@ThomasHMAC if the pandas version is different from the one in `setup.cfg`, could you please update that file as well

2021-01-19 16:35 UTC, jerdra requested changes
One more comment as I'm trying to run this script for MODSOCCS:

Can you update the script to be able to run participants individually? It's much easier to debug when you don't force a run of all participants. When one subject has an issue w/its EA data the whole script shouldn't have to fail (see comment w/gracefully handling a TypeError)

2021-01-19 16:35 UTC, jerdra commented on bin/dm_parse_ea.py
> +    ].where(mask is False)
```suggestion
    combo2["rating_duration"] = combo2["onset"].shift(-1) - combo2[
        "onset"
    ].where(mask)
```

I get an error w/pandas 1.0.3 since "mask is False" evaluates to a single element

2021-01-19 16:35 UTC, jerdra commented on bin/dm_parse_ea.py
> +    time_to_subtract = int(log_file.Duration[log_file.Code == "MRI_start"])
doesn't gracefully handle cases where integer conversion cannot be performed

2021-01-19 16:39 UTC, jerdra commented on bin/dm_parse_ea.py
> +    ].where(mask is False)
also I think `DataFrame.diff()` can perform the above operation in a much cleaner fashion?

2021-01-19 16:51 UTC, jerdra requested changes

2021-01-19 16:51 UTC, jerdra commented on bin/dm_parse_ea.py
> +            )
```suggestion
            logger.warning(
                "gold standard is shorter than the number of pt "
                f"ratings. pt ratings truncated, block: {block_name}"
            )
```

2021-01-19 16:51 UTC, jerdra commented on bin/dm_parse_ea.py
> +            )
```suggestion
            logger.warning(
                "number of pt ratings is shorter than the number "
                f"of gold std, gold std truncated, block: {block_name}"
            )
```

2021-01-19 18:57 UTC, jerdra commented
@josephmje i've made some updates to the script to resolve my own comments, can you do a quick review whenever you get the chance? Mostly so we can get it within the code-base for SPN20 QC?

This script needs a full re-write eventually, its barely maintainable :shrug:

Thanks Dawn/Thomas for dealing with this beast for the most part!

2021-01-19 18:57 UTC, jerdra approved these changes

2021-01-19 19:48 UTC, josephmje approved these changes

2021-01-19 19:48 UTC, merged