Updated EA parse to remove button press during scan response
TIGRLab/datman pull request #298
Opened 2021-02-12 03:30 UTC by ThomasHMAC

2021-02-12 03:30 UTC, pep8speaks commented
Hello @ThomasHMAC, thank you for submitting the Pull Request!

* In the file [`bin/dm_parse_ea.py`](https://github.com/TIGRLab/datman/blob/3cf0d6f8419d5102bd9959a3e8e72e548183b83d/bin/dm_parse_ea.py):

> [Line 198:14](https://github.com/TIGRLab/datman/blob/3cf0d6f8419d5102bd9959a3e8e72e548183b83d/bin/dm_parse_ea.py#L198): [E712](https://duckduckgo.com/?q=pep8%20E712) comparison to False should be 'if cond is False:' or 'if not cond:'



To test for issues locally, `pip install flake8` and then run `flake8 datman`.

2021-02-12 15:49 UTC, jerdra requested changes

2021-02-12 15:49 UTC, jerdra commented on bin/dm_parse_ea.py
> +            indexes_to_drop.append(index - 2)
Can you add a comment describing why the current index and 2 indices beforehand need to be dropped? Mostly so we don't have a magic number in there that people in the future wouldn't understand!

2021-02-12 15:49 UTC, jerdra commented on bin/dm_parse_ea.py
> +        )
Maybe include the number of "chunks" being dropped here for QC purposes (i.e if an abnormally large number of indices got dropped). 

```suggestion
        logger.warning(
            f"Removed {len(indexes_to_drop)/2} registered ratings that occurred before or after actual rating"
        )
```

2021-02-12 15:49 UTC, jerdra commented on bin/dm_parse_ea.py
> +            indexes_to_drop_1.append(index - 1)
I think a "why" comment is needed here as well, might just be me, but I'm not really sure why we dropped i, i-2, and now i,i-1!

2021-02-12 15:49 UTC, jerdra commented on bin/dm_parse_ea.py
> +        logger.warning("Removed rating registered followed scanner responses")
Same as above logging comment re: including the number of ratings dropped

2021-02-12 15:49 UTC, jerdra commented on bin/dm_parse_ea.py
> +        else "n/a"
maybe it might be a good idea to use to use `pd.NA` here to avoid having a mixed data-type column

2021-02-12 15:49 UTC, jerdra commented on bin/dm_parse_ea.py
> +        lambda x: vid_info[x]["stim_file"] if x in vid_info else "n/a"
same as above `pd.NA` comment

2021-02-12 15:49 UTC, jerdra commented on bin/dm_parse_ea.py
> +        log_cleaned = clean_logfile(log)
could this be outside the try/catch block? It looks like `clean_logfile` is mostly if not entirely safe

2021-02-12 15:49 UTC, jerdra commented on bin/dm_task_files.py
> +            pass
```suggestion
        os.makedirs(dest_folder, exist_ok=True)
```

Unless you want it to error out if intermediate directories don't exist!

2021-03-12 18:47 UTC, jerdra approved these changes

2021-03-12 20:33 UTC, josephmje approved these changes

2021-03-12 20:47 UTC, merged