Adding FACES parser to datman
TIGRLab/datman pull request #301
Opened 2021-04-20 16:13 UTC by benselby

Adding an old script for parsing OPT's FACES task to datman.

2021-04-20 16:13 UTC, pep8speaks commented
Hello @benselby, thank you for submitting the Pull Request!

* In the file [`bin/dm_parse_faces.py`](https://github.com/TIGRLab/datman/blob/4cff15ab00f592c9e05ff79a35af2213ecef7a85/bin/dm_parse_faces.py):

> [Line 6:80](https://github.com/TIGRLab/datman/blob/4cff15ab00f592c9e05ff79a35af2213ecef7a85/bin/dm_parse_faces.py#L6): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 14:58](https://github.com/TIGRLab/datman/blob/4cff15ab00f592c9e05ff79a35af2213ecef7a85/bin/dm_parse_faces.py#L14): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 17:81](https://github.com/TIGRLab/datman/blob/4cff15ab00f592c9e05ff79a35af2213ecef7a85/bin/dm_parse_faces.py#L17): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (89 > 80 characters)
> [Line 35:9](https://github.com/TIGRLab/datman/blob/4cff15ab00f592c9e05ff79a35af2213ecef7a85/bin/dm_parse_faces.py#L35): [E126](https://duckduckgo.com/?q=pep8%20E126) continuation line over-indented for hanging indent
> [Line 36:9](https://github.com/TIGRLab/datman/blob/4cff15ab00f592c9e05ff79a35af2213ecef7a85/bin/dm_parse_faces.py#L36): [E123](https://duckduckgo.com/?q=pep8%20E123) closing bracket does not match indentation of opening bracket's line
> [Line 40:1](https://github.com/TIGRLab/datman/blob/4cff15ab00f592c9e05ff79a35af2213ecef7a85/bin/dm_parse_faces.py#L40): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 0
> [Line 44:1](https://github.com/TIGRLab/datman/blob/4cff15ab00f592c9e05ff79a35af2213ecef7a85/bin/dm_parse_faces.py#L44): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 60:31](https://github.com/TIGRLab/datman/blob/4cff15ab00f592c9e05ff79a35af2213ecef7a85/bin/dm_parse_faces.py#L60): [W605](https://duckduckgo.com/?q=pep8%20W605) invalid escape sequence '\d'
> [Line 139:1](https://github.com/TIGRLab/datman/blob/4cff15ab00f592c9e05ff79a35af2213ecef7a85/bin/dm_parse_faces.py#L139): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 157:48](https://github.com/TIGRLab/datman/blob/4cff15ab00f592c9e05ff79a35af2213ecef7a85/bin/dm_parse_faces.py#L157): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 167:1](https://github.com/TIGRLab/datman/blob/4cff15ab00f592c9e05ff79a35af2213ecef7a85/bin/dm_parse_faces.py#L167): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 174:1](https://github.com/TIGRLab/datman/blob/4cff15ab00f592c9e05ff79a35af2213ecef7a85/bin/dm_parse_faces.py#L174): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 180:1](https://github.com/TIGRLab/datman/blob/4cff15ab00f592c9e05ff79a35af2213ecef7a85/bin/dm_parse_faces.py#L180): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 182:1](https://github.com/TIGRLab/datman/blob/4cff15ab00f592c9e05ff79a35af2213ecef7a85/bin/dm_parse_faces.py#L182): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 184:1](https://github.com/TIGRLab/datman/blob/4cff15ab00f592c9e05ff79a35af2213ecef7a85/bin/dm_parse_faces.py#L184): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 203:1](https://github.com/TIGRLab/datman/blob/4cff15ab00f592c9e05ff79a35af2213ecef7a85/bin/dm_parse_faces.py#L203): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 205:21](https://github.com/TIGRLab/datman/blob/4cff15ab00f592c9e05ff79a35af2213ecef7a85/bin/dm_parse_faces.py#L205): [E126](https://duckduckgo.com/?q=pep8%20E126) continuation line over-indented for hanging indent
> [Line 211:21](https://github.com/TIGRLab/datman/blob/4cff15ab00f592c9e05ff79a35af2213ecef7a85/bin/dm_parse_faces.py#L211): [E123](https://duckduckgo.com/?q=pep8%20E123) closing bracket does not match indentation of opening bracket's line
> [Line 212:21](https://github.com/TIGRLab/datman/blob/4cff15ab00f592c9e05ff79a35af2213ecef7a85/bin/dm_parse_faces.py#L212): [E127](https://duckduckgo.com/?q=pep8%20E127) continuation line over-indented for visual indent
> [Line 217:1](https://github.com/TIGRLab/datman/blob/4cff15ab00f592c9e05ff79a35af2213ecef7a85/bin/dm_parse_faces.py#L217): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 219:1](https://github.com/TIGRLab/datman/blob/4cff15ab00f592c9e05ff79a35af2213ecef7a85/bin/dm_parse_faces.py#L219): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 220:13](https://github.com/TIGRLab/datman/blob/4cff15ab00f592c9e05ff79a35af2213ecef7a85/bin/dm_parse_faces.py#L220): [F841](https://duckduckgo.com/?q=pep8%20F841) local variable 'sub_id' is assigned to but never used
> [Line 221:1](https://github.com/TIGRLab/datman/blob/4cff15ab00f592c9e05ff79a35af2213ecef7a85/bin/dm_parse_faces.py#L221): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 223:49](https://github.com/TIGRLab/datman/blob/4cff15ab00f592c9e05ff79a35af2213ecef7a85/bin/dm_parse_faces.py#L223): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 224:29](https://github.com/TIGRLab/datman/blob/4cff15ab00f592c9e05ff79a35af2213ecef7a85/bin/dm_parse_faces.py#L224): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 224:70](https://github.com/TIGRLab/datman/blob/4cff15ab00f592c9e05ff79a35af2213ecef7a85/bin/dm_parse_faces.py#L224): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 225:27](https://github.com/TIGRLab/datman/blob/4cff15ab00f592c9e05ff79a35af2213ecef7a85/bin/dm_parse_faces.py#L225): [E124](https://duckduckgo.com/?q=pep8%20E124) closing bracket does not match visual indentation
> [Line 226:1](https://github.com/TIGRLab/datman/blob/4cff15ab00f592c9e05ff79a35af2213ecef7a85/bin/dm_parse_faces.py#L226): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 227:66](https://github.com/TIGRLab/datman/blob/4cff15ab00f592c9e05ff79a35af2213ecef7a85/bin/dm_parse_faces.py#L227): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 230:1](https://github.com/TIGRLab/datman/blob/4cff15ab00f592c9e05ff79a35af2213ecef7a85/bin/dm_parse_faces.py#L230): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 237:1](https://github.com/TIGRLab/datman/blob/4cff15ab00f592c9e05ff79a35af2213ecef7a85/bin/dm_parse_faces.py#L237): [E305](https://duckduckgo.com/?q=pep8%20E305) expected 2 blank lines after class or function definition, found 1

To test for issues locally, `pip install flake8` and then run `flake8 datman`.

2021-04-29 16:00 UTC, kyjimmy requested changes
Mostly style changes with a few minor changes with `docopt` usage and the extraction of `duration`.

2021-04-29 16:00 UTC, kyjimmy commented on bin/dm_parse_faces.py
> +Usage: dm_parse_faces.py [options] <study> [<session>] [--output-dir=<out_dir>]
```suggestion
Usage:
    dm_parse_faces.py [options] <study>
    dm_parse_faces.py [options] <study> [<session>]
    dm_parse_faces.py [options] <study> [<session>] [--output-dir=<out_dir>]
```

2021-04-29 16:00 UTC, kyjimmy commented on bin/dm_parse_faces.py
> +    <session>   Datman name of session to process e.g. OPT01_UP1_UP10044_02_03
```suggestion
    <session>   Datman name of session to process e.g. OPT01_UP1_UP10004_02_01
```

2021-04-29 16:00 UTC, kyjimmy commented on bin/dm_parse_faces.py
> +    <session>   Datman name of session to process e.g. OPT01_UP1_UP10044_02_03
No data inside that participant's folder.

2021-04-29 16:00 UTC, kyjimmy commented on bin/dm_parse_faces.py
> +Outputs the trial number, onset time, accurracy, and reaction time values for each trial.
```suggestion
Outputs the trial number, onset time, accurracy, and reaction time values \
    for each trial.
```

2021-04-29 16:00 UTC, kyjimmy commented on bin/dm_parse_faces.py
> +Outputs the trial number, onset time, accurracy, and reaction time values for each trial.
pep8 maximum characters issue

2021-04-29 16:00 UTC, kyjimmy commented on bin/dm_parse_faces.py
> +    --dry-run       Don't actually write any output
```suggestion
    --output-dir=<out_dir>  Specify an alternate output directory
    --debug                 Set log level to debug
    --dry-run               Don't actually write any output
```

2021-04-29 16:00 UTC, kyjimmy commented on bin/dm_parse_faces.py
> +        )
```suggestion
logging.basicConfig(level=logging.WARN,
                    format="[%(name)s] %(levelname)s: %(message)s")
```

2021-04-29 16:00 UTC, kyjimmy commented on bin/dm_parse_faces.py
> +def _esc_fname(match):
```suggestion


def _esc_fname(match):
```

2021-04-29 16:00 UTC, kyjimmy commented on bin/dm_parse_faces.py
> +
```suggestion


```

2021-04-29 16:00 UTC, kyjimmy commented on bin/dm_parse_faces.py
> +
```suggestion

```

2021-04-29 16:00 UTC, kyjimmy commented on bin/dm_parse_faces.py
> +            )
```suggestion
            logger.error(f"Skipping task folder with malformed ID {ses}")
```

2021-04-29 16:00 UTC, kyjimmy commented on bin/dm_parse_faces.py
> +        ses_path = os.path.join(task_path, ses)
```suggestion
        ses_path = os.path.join(task_path, ses)
```

2021-04-29 16:00 UTC, kyjimmy commented on bin/dm_parse_faces.py
> +
```suggestion

```

2021-04-29 16:00 UTC, kyjimmy commented on bin/dm_parse_faces.py
> +
```suggestion

```

2021-04-29 16:00 UTC, kyjimmy commented on bin/dm_parse_faces.py
> +
```suggestion

```

2021-04-29 16:00 UTC, kyjimmy commented on bin/dm_parse_faces.py
> +
```suggestion

```

2021-04-29 16:00 UTC, kyjimmy commented on bin/dm_parse_faces.py
> +
```suggestion

```

2021-04-29 16:00 UTC, kyjimmy commented on bin/dm_parse_faces.py
> +                    get_event_value(b, 'StimSlideOnsetToOnsetTime:'),
```suggestion
                    get_event_value(b, 'StimSlide.OnsetToOnsetTime:'),
```

2021-04-29 16:00 UTC, kyjimmy commented on bin/dm_parse_faces.py
> +
```suggestion

```

2021-04-29 16:00 UTC, kyjimmy commented on bin/dm_parse_faces.py
> +
```suggestion
                "onset": np.float,
                "duration": np.float,
                "response_time": np.float,
                "accuracy": np.float,
                "correct_response": np.float,
                "participant_response": np.float
            })\
                .astype({
                    "correct_response": "Int64",
                    "participant_response": "Int64",
                    "accuracy": "Int64"
                })

            # log_head, log_tail = os.path.split(eprimefile)
            # sub_id = os.path.basename(log_head)

```

2021-04-29 16:00 UTC, kyjimmy commented on bin/dm_parse_faces.py
> +
```suggestion
                out_dir = os.path.join(nii_path,
                                       ident.get_full_subjectid_with_timepoint()
                                       )

            file_name = os.path.join(out_dir, f"{ses}_FACES.tsv")

```

2021-04-29 16:00 UTC, kyjimmy commented on bin/dm_parse_faces.py
> +
```suggestion


```

2021-04-29 16:00 UTC, kyjimmy commented on bin/dm_parse_faces.py
> +            if not dryrun:
```suggestion
            if not dryrun:
                os.makedirs(os.path.dirname(file_name), exist_ok=True)
```

2021-05-18 14:38 UTC, benselby commented on bin/dm_parse_faces.py
> +    <session>   Datman name of session to process e.g. OPT01_UP1_UP10044_02_03
There is task data in OPT/task in the archive for this pt.

2021-06-16 17:24 UTC, jerdra commented
Will close this PR and take over, thanks for the comments @kyjimmy, am integrating them rn and will re-open with your suggestions!

2021-06-16 17:24 UTC, closed without merging