Make datman easier to install and use
TIGRLab/datman pull request #303
Opened 2021-04-30 16:59 UTC by DESm1th

This pull request adds:

- Fixes for some bugs that arise when running without a dashboard
- Well commented configuration templates in `assets/config_templates` that can be used by anyone without access to our datman-config repo
- A dockerfile documenting how tigrlab/datman:0.1 was built
- Updates and fixes to our documentation pages on how to install and configure datman

2021-04-30 16:59 UTC, pep8speaks commented
Hello @DESm1th, thank you for submitting the Pull Request!









* In the file [`bin/dm_sftp.py`](https://github.com/TIGRLab/datman/blob/cd5bb049e5d0925a2fc05c82822c125aa234a6b7/bin/dm_sftp.py):

> [Line 94:34](https://github.com/TIGRLab/datman/blob/cd5bb049e5d0925a2fc05c82822c125aa234a6b7/bin/dm_sftp.py#L94): [F541](https://duckduckgo.com/?q=pep8%20F541) f-string is missing placeholders













* In the file [`tests/test_utils.py`](https://github.com/TIGRLab/datman/blob/cd5bb049e5d0925a2fc05c82822c125aa234a6b7/tests/test_utils.py):

> [Line 131:5](https://github.com/TIGRLab/datman/blob/cd5bb049e5d0925a2fc05c82822c125aa234a6b7/tests/test_utils.py#L131): [E125](https://duckduckgo.com/?q=pep8%20E125) continuation line with same indent as next logical line
> [Line 131:9](https://github.com/TIGRLab/datman/blob/cd5bb049e5d0925a2fc05c82822c125aa234a6b7/tests/test_utils.py#L131): [E121](https://duckduckgo.com/?q=pep8%20E121) continuation line under-indented for hanging indent

To test for issues locally, `pip install flake8` and then run `flake8 datman`.

2021-05-04 13:28 UTC, josephmje reviewed
Thanks for this @DESm1th! Especially all of that reformatting of the docs. I've yet to go over the config files but had 2 minor comments to start.

2021-05-04 13:28 UTC, josephmje commented on assets/config_templates/main_config.yml
> +# to read it you must set the DM_CONFIG environment variable its full path.
```suggestion
# to read it you must set the DM_CONFIG environment variable to this file's full path.
```

2021-05-04 15:52 UTC, DESm1th commented
Thanks for the feedback Mike! :)

2021-05-04 19:44 UTC, josephmje submitted a review, later dismissed

2021-10-05 15:41 UTC, jerdra reviewed
Thanks for putting this together Dawn! Just had a few verrry minor items that could maybe be addressed in a separate PR but i thought would be worth mentioning!

2021-10-05 15:41 UTC, jerdra commented on bin/dm_redcap_scan_completed.py
> +
should `get_setting` be defined in the Config object instead?

2021-10-05 19:23 UTC, DESm1th commented on README.rst
> +Datman runs a standard QC pipeline on all major datatypes. It largely does this using the `qcmon <https://github.com/josephdviviano/qcmon>`_ project.
Whoops! Thanks for catching that

2021-10-05 19:26 UTC, DESm1th commented on bin/dm_link_sprl.py
>      logger.setLevel(logging.WARN)
Nope, none at all (except in places where we add a server log handler). This is just a historical thing leftover from the days when we joe/tom/I had three different ideas about how it should be done. I've always meant to clean up these old instances though

2021-10-05 19:28 UTC, DESm1th commented on bin/dm_redcap_scan_completed.py
> +
I _think_ there was a good reason at the time why I put it here and not in config.py, but I can't currently remember what that was. So maybe I should move it over? I'll try to job my memory on this one

2021-12-20 18:51 UTC, josephmje commented
Sorry about the delay on this @DESm1th! Is this now ready for review?

2022-01-04 19:17 UTC, DESm1th commented
> Sorry about the delay on this @DESm1th! Is this now ready for review?

It is!

2022-02-09 16:40 UTC, josephmje requested changes

2022-02-09 16:40 UTC, josephmje commented on Dockerfile
> +# Install dcm2niix/v1.0.20210317
Could we upgrade the version of dcm2niix here?

2022-02-09 18:31 UTC, DESm1th commented on Dockerfile
> +# Install dcm2niix/v1.0.20210317
Absolutely! Thanks for catching that. What version should I add here? Just the newest?

2022-02-22 14:46 UTC, josephmje commented on Dockerfile
> +# Install dcm2niix/v1.0.20210317
Hey Dawn, sorry for the late reply. Yes, it would be v1.0.20211006

@jerdra Do you know if this latest version is correct or the 2019 version RE the OPT slice timing?

2022-02-22 15:10 UTC, jerdra commented on Dockerfile
> +# Install dcm2niix/v1.0.20210317
its probably fine given that we don't use slice-timing for fMRI scans anyway. The diffusion scans aren't affected

2022-02-23 20:14 UTC, josephmje approved these changes

2022-04-22 20:01 UTC, jerdra approved these changes

2022-04-25 17:48 UTC, merged