Added inital xnat_to_bids function and error checking for it
TIGRLab/datman pull request #317
Opened 2021-11-16 17:22 UTC by slimnsour

This is my base work for getting xnat_to_bids working on our system. This adds the function `xnat_to_bids` that pulls the data directly from xnat into a tmp folder, and then dcm2bids is run on that tmp folder with an appropriate json for that study. This is called instead of the usual xnat to nii pull if you call `dm_xnat_extract.py` with the tag `--use-dcm2bids`. Several arguments for dcm2bids are also allowed to be controlled (like `--dcm-config`, `--forceDcm2niix`, and `--clobber`). 

I would greatly appreciate feedback on this! Right now I have some design decisions that I'm unsure of as well:
 - The default dcm2bids json location for each study is at `/archive/data/$STUDY/metadata/dcm2bids.json`. I think this might be a good idea instead of forcing it into the yamls for each of the studies, since the jsons mapping each study could overwhelm the file contents. Instead, we can have a separate location (its own repo or a folder or in [datman-config](https://github.com/TIGRLab/datman-config)) for all the jsons and then soft link them to `metadata/dcm2bids.json`. An example folder is already in [our bids_dev repo](https://github.com/TIGRLab/bids_dev/tree/main/config).
 - The default bids folder is at `/archive/data/$STUDY/data/bids`. I believe this makes sense, especially with the option `--bids-out` that allows you to override it for testing purposes.
 - Dcm2Bids is currently being imported as a package and being called as a function. I did this as a configurable option since [our Dcm2Bids](https://github.com/TIGRLab/Dcm2Bids) is already a python package, but this would require datman to depend on Dcm2Bids now. I'm open to other options, namely using a singularity container. I already have the container with the newest dcm2niix and our dcm2bids installed, it's just a matter of switching it out if we want to use that instead.
 
I still have other features I might add in the future (fixing fmap json intendedFor's, defacing), but I'd like to get the base functionality out there to get your guys' opinions on it.

2021-11-17 14:28 UTC, jerdra requested changes
Good work putting this together @slimnsour! Just have some comments on code-styling and 1 bigger ask to simplify the CLI interface. Lmk if you have questions :)

2021-11-17 14:28 UTC, jerdra commented on bin/dm_xnat_extract.py
> +                        clobber=clobber)
I'd refactor this and bundle these parameters as a dcm2bids Config object/dataclass

2021-11-17 14:28 UTC, jerdra commented on bin/dm_xnat_extract.py
> +            process_experiment(xnat, project, experiment)
I'm even more convinced that we should use a sub-parser now! You could set up `subparser.set_defaults(function=<target_func>)` to simplify the logic:

https://stackoverflow.com/questions/49038616/argparse-subparsers-with-functions

2021-11-17 14:28 UTC, jerdra commented on bin/dm_xnat_extract.py
> +    # Make temporary folder for this subject
```suggestion
  
```
unnecessary comment

2021-11-17 14:28 UTC, jerdra commented on bin/dm_xnat_extract.py
> +        # Pull each of the scans from the subject's experiment
```suggestion
        
```
also not needed

2021-11-17 14:28 UTC, jerdra commented on bin/dm_xnat_extract.py
> +            if not scanTemp:
```suggestion
            scan_temp = get_dicom_archive_from_xnat(xnat, scan, tempdir)
            if not scan_temp:
```

2021-11-17 14:28 UTC, jerdra commented on bin/dm_xnat_extract.py
> +        # Once all the scans are downloaded, run dcm2bids on the pulled data
```suggestion
     
```

2021-11-17 14:28 UTC, jerdra commented on bin/dm_xnat_extract.py
> +                                clobber=clobber, forceDcm2niix=forceDcm2niix, log_level="INFO")
```suggestion
        sub_dcm_dir = os.path.join(tempdir, experiment_label, "scans")
        try:
            dcm2bids_app = Dcm2bids(sub_dcm_dir, bids_sub, dcm2bids_config, output_dir=bids_out, session=bids_ses, 
                                clobber=clobber, forceDcm2niix=forceDcm2niix, log_level="INFO")
```

2021-11-17 14:33 UTC, jerdra commented
> I would greatly appreciate feedback on this! Right now I have some design decisions that I'm unsure of as well:
> 
> * The default dcm2bids json location for each study is at `/archive/data/$STUDY/metadata/dcm2bids.json`. I think this might be a good idea instead of forcing it into the yamls for each of the studies, since the jsons mapping each study could overwhelm the file contents. Instead, we can have a separate location (its own repo or a folder or in [datman-config](https://github.com/TIGRLab/datman-config)) for all the jsons and then soft link them to `metadata/dcm2bids.json`. An example folder is already in [our bids_dev repo](https://github.com/TIGRLab/bids_dev/tree/main/config).

Agreed, I think this is a good solution

> * The default bids folder is at `/archive/data/$STUDY/data/bids`. I believe this makes sense, especially with the option `--bids-out` that allows you to override it for testing purposes.

Perf! This is how `bidsify.py` currently works as well

> * Dcm2Bids is currently being imported as a package and being called as a function. I did this as a configurable option since [our Dcm2Bids](https://github.com/TIGRLab/Dcm2Bids) is already a python package, but this would require datman to depend on Dcm2Bids now. I'm open to other options, namely using a singularity container. I already have the container with the newest dcm2niix and our dcm2bids installed, it's just a matter of switching it out if we want to use that instead.

Maybe we could have datman have a `datman[bids]` setup.cfg option so that it becomes an optional dependency? This would require some refactoring (i.e moving dcm2bids import into a function, perhaps the one called by a subparser if that's what we end up going for)

2021-11-17 16:41 UTC, DESm1th requested changes
This looks good Salim, thank you! It looks like the 'making symlinks for the legacy datman folders' part was abandoned though. Without it a lot of our bin scripts and stuff will break at the moment so we might have to hold off on running nightly with the dcm2bids flag for a while

2021-11-17 16:41 UTC, DESm1th commented on bin/dm_xnat_extract.py
> +                        clobber=clobber)
I second Jer's suggestion here

2021-11-17 16:41 UTC, DESm1th commented on bin/dm_xnat_extract.py
> +                                clobber=clobber, forceDcm2niix=forceDcm2niix, log_level="INFO")
Just to add on forceDcm2niix should probably also be force_dcm2niix

2021-11-17 16:49 UTC, josephmje commented on bin/dm_xnat_extract.py
> +                except datman.scanid.ParseException:
Should this be a `FileNotFoundError` instead?

2021-11-18 20:43 UTC, pep8speaks commented
Hello @slimnsour, Thank you for updating!

* In the file [`bin/dm_xnat_extract.py`](https://github.com/TIGRLab/datman/blob/7bb514f00292e385eadfcdee5a7f69b01c34bef1/bin/dm_xnat_extract.py):

> [Line 144:1](https://github.com/TIGRLab/datman/blob/7bb514f00292e385eadfcdee5a7f69b01c34bef1/bin/dm_xnat_extract.py#L144): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 315:81](https://github.com/TIGRLab/datman/blob/7bb514f00292e385eadfcdee5a7f69b01c34bef1/bin/dm_xnat_extract.py#L315): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (113 > 80 characters)
> [Line 323:81](https://github.com/TIGRLab/datman/blob/7bb514f00292e385eadfcdee5a7f69b01c34bef1/bin/dm_xnat_extract.py#L323): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (96 > 80 characters)
> [Line 326:33](https://github.com/TIGRLab/datman/blob/7bb514f00292e385eadfcdee5a7f69b01c34bef1/bin/dm_xnat_extract.py#L326): [E127](https://duckduckgo.com/?q=pep8%20E127) continuation line over-indented for visual indent
> [Line 326:43](https://github.com/TIGRLab/datman/blob/7bb514f00292e385eadfcdee5a7f69b01c34bef1/bin/dm_xnat_extract.py#L326): [F821](https://duckduckgo.com/?q=pep8%20F821) undefined name 'study'
> [Line 332:81](https://github.com/TIGRLab/datman/blob/7bb514f00292e385eadfcdee5a7f69b01c34bef1/bin/dm_xnat_extract.py#L332): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (118 > 80 characters)
> [Line 332:119](https://github.com/TIGRLab/datman/blob/7bb514f00292e385eadfcdee5a7f69b01c34bef1/bin/dm_xnat_extract.py#L332): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 333:81](https://github.com/TIGRLab/datman/blob/7bb514f00292e385eadfcdee5a7f69b01c34bef1/bin/dm_xnat_extract.py#L333): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (113 > 80 characters)
> [Line 337:29](https://github.com/TIGRLab/datman/blob/7bb514f00292e385eadfcdee5a7f69b01c34bef1/bin/dm_xnat_extract.py#L337): [E127](https://duckduckgo.com/?q=pep8%20E127) continuation line over-indented for visual indent
> [Line 337:45](https://github.com/TIGRLab/datman/blob/7bb514f00292e385eadfcdee5a7f69b01c34bef1/bin/dm_xnat_extract.py#L337): [F821](https://duckduckgo.com/?q=pep8%20F821) undefined name 'experiment_label'
> [Line 337:81](https://github.com/TIGRLab/datman/blob/7bb514f00292e385eadfcdee5a7f69b01c34bef1/bin/dm_xnat_extract.py#L337): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (83 > 80 characters)
> [Line 358:81](https://github.com/TIGRLab/datman/blob/7bb514f00292e385eadfcdee5a7f69b01c34bef1/bin/dm_xnat_extract.py#L358): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (83 > 80 characters)
> [Line 359:29](https://github.com/TIGRLab/datman/blob/7bb514f00292e385eadfcdee5a7f69b01c34bef1/bin/dm_xnat_extract.py#L359): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 361:1](https://github.com/TIGRLab/datman/blob/7bb514f00292e385eadfcdee5a7f69b01c34bef1/bin/dm_xnat_extract.py#L361): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 363:76](https://github.com/TIGRLab/datman/blob/7bb514f00292e385eadfcdee5a7f69b01c34bef1/bin/dm_xnat_extract.py#L363): [F821](https://duckduckgo.com/?q=pep8%20F821) undefined name 'log_level'
> [Line 363:81](https://github.com/TIGRLab/datman/blob/7bb514f00292e385eadfcdee5a7f69b01c34bef1/bin/dm_xnat_extract.py#L363): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (85 > 80 characters)

To test for issues locally, `pip install flake8` and then run `flake8 datman`.

2021-11-19 14:58 UTC, jerdra commented
@slimnsour maybe instead of a sub-parser we could use `ArgumentParser.add_argument_group` like @josephmje did in #318?

2021-11-19 17:23 UTC, slimnsour commented
> @slimnsour maybe instead of a sub-parser we could use `ArgumentParser.add_argument_group` like @josephmje did in #318?
> 
> It would achieve separation of bids options from base options to mitigate overcrowding as we had originally wanted

Great suggestion! I've added that to the newest commit. 

For context, the subparsers in argparse (from my testing) requires that the option to select the subparser be the very first positional argument choose between the subparsers. So, if we wanted to have subparsers to separate between extracting using our usual datman way and dcm2bids, we would have to call it like `dm_xnat_extract.py {datman, dcm2bids} <study> ...`, which is _fine_, but it would break our current management scripts that assume `<study>` to be the first argument. If anyone can figure out a good way to do this then I would happy to implement it but it might be out of the scope of this PR.

Here's the new output of `dm_xnat_extract.py --help` using `argparse`:

```
usage: dm_xnat_extract.py [-h] [--blacklist FILE] [--server URL] [-u USER]
                          [--dont-update-dashboard] [-t [tag,...]]
                          [--use-dcm2bids] [--bids-out DIR]
                          [--dcm-config FILE] [--keep-dcm] [--force-dcm2niix]
                          [--clobber] [-d] [-q] [-v] [-n]
                          study [experiment]

Extracts data from XNAT archive folders into a few well-known formats.

optional arguments:
  -h, --help            show this help message and exit

Options for choosing data from XNAT to extract:
  study                 Nickname of the study to process
  experiment            Full ID of the experiment to process (default: None)
  --blacklist FILE      Table listing series to ignore override the default
                        metadata/blacklist.csv (default: None)
  --server URL          XNAT server to connect to, overrides the server
                        defined in the configuration files. (default: None)
  -u USER, --username USER
                        XNAT username. If specified then the environment
                        variables (or any credential files) are ignored and
                        you are prompted for a password. Note that if multiple
                        servers are configured for a study the login used
                        should be valid for all servers.. (default: None)
  --dont-update-dashboard
                        Dont update the dashboard database (default: False)
  -t [tag,...], --tag [tag,...]
                        List of scan tags to download (default: None)

Options for using dcm2bids:
  --use-dcm2bids        Pull xnat data and convert to bids using dcm2bids
                        (default: False)
  --bids-out DIR        Path to output bids folder (default: None)
  --dcm-config FILE     Path to dcm2bids config file (default: None)
  --keep-dcm            Keep raw dcm pulled from xnat in temp folder (default:
                        False)
  --force-dcm2niix      Force dcm2niix to be rerun in dcm2bids (default:
                        False)
  --clobber             Clobber previous bids data (default: False)

Options for logging and debugging:
  -d, --debug           Show debug messages (default: False)
  -q, --quiet           Minimal logging (default: False)
  -v, --verbose         Maximal logging (default: False)
  -n, --dry-run         Do nothing (default: False)
```

2021-11-19 17:24 UTC, slimnsour commented on bin/dm_xnat_extract.py
> +                except datman.scanid.ParseException:
Good catch! Fixed in f7486cb1a0cacf80a2f2ee0875159a7e5d5af3cb

2021-11-19 17:25 UTC, slimnsour commented on bin/dm_xnat_extract.py
> +                                clobber=clobber, forceDcm2niix=forceDcm2niix, log_level="INFO")
Thanks, fixed in f7486cb1a0cacf80a2f2ee0875159a7e5d5af3cb

2021-11-19 17:26 UTC, slimnsour commented on bin/dm_xnat_extract.py
> +                                clobber=clobber, forceDcm2niix=forceDcm2niix, log_level="INFO")
Thanks, fixed in f7486cb1a0cacf80a2f2ee0875159a7e5d5af3cb

2021-11-19 17:27 UTC, slimnsour commented on bin/dm_xnat_extract.py
> +        # Once all the scans are downloaded, run dcm2bids on the pulled data
Removed unnecessary comments in f7486cb1a0cacf80a2f2ee0875159a7e5d5af3cb

2021-11-19 17:29 UTC, slimnsour commented on bin/dm_xnat_extract.py
> +            if not scanTemp:
Thanks for the catch, updated in f7486cb1a0cacf80a2f2ee0875159a7e5d5af3cb

2021-11-19 17:30 UTC, slimnsour commented on bin/dm_xnat_extract.py
> +        # Pull each of the scans from the subject's experiment
Removed unnecessary comments in f7486cb

2021-11-19 17:31 UTC, slimnsour commented on bin/dm_xnat_extract.py
> +    # Make temporary folder for this subject
Removed unnecessary comments f7486cb

2021-11-19 17:31 UTC, slimnsour commented on bin/dm_xnat_extract.py
> +    except Exception as e:
Good catch! Fixed in f7486cb

2021-11-19 17:32 UTC, slimnsour commented on bin/dm_xnat_extract.py
> +    --clobber                Clobber previous bids data
Added the dataclass in the new commits! Thanks for the suggestion

2021-11-19 17:33 UTC, slimnsour commented on bin/dm_xnat_extract.py
> +                        clobber=clobber)
Added dataclass in the new commits, great suggestion!

2021-11-19 17:33 UTC, slimnsour commented on bin/dm_xnat_extract.py
> +            process_experiment(xnat, project, experiment)
Added the new argparse parser in the new commits but no subparser, see https://github.com/TIGRLab/datman/pull/317#issuecomment-974262017

2021-11-19 17:37 UTC, josephmje commented on bin/dm_xnat_extract.py
> +    --use-dcm2bids           Pull xnat data and convert to bids using dcm2bids
`argparse` should be able to build the usage arguments and options dynamically so the old docopt code in the docstring isn't as necessary.

2021-11-19 17:37 UTC, josephmje commented on bin/dm_xnat_extract.py
> +from pathlib import Path
This is nitpicky but we don't need both `pathlib` and `os.path`. Stick with one.

2021-11-19 17:37 UTC, josephmje commented on bin/dm_xnat_extract.py
> +    """Ensure a given directory exists."""
```suggestion
    """Ensure a given file exists."""
```

2021-11-19 17:37 UTC, josephmje commented on bin/dm_xnat_extract.py
> +        raise parser.error(f"Directory does not exist: <{path}>")
```suggestion
        raise parser.error(f"File does not exist: <{path}>")
```

2021-11-19 17:37 UTC, josephmje commented on bin/dm_xnat_extract.py
> +        action="store",
```suggestion
        action="store",
        required=True,
```

2021-11-19 17:37 UTC, josephmje commented on bin/dm_xnat_extract.py
> +        type=lambda x: Path(x).isfile(),
```suggestion
        type=lambda x: _is_file(x, parser),
```

2021-11-19 17:37 UTC, josephmje commented on bin/dm_xnat_extract.py
> +        help="Pull xnat data and convert to bids using dcm2bids"
Should the `--use-dcm2bids` option exist outside of this? And then, **only** if that option is used, the `g_dcm2bids` options are exposed.

2021-11-19 18:42 UTC, slimnsour commented on bin/dm_xnat_extract.py
> +        action="store",
I committed this without realizing it will break: `TypeError: 'required' is an invalid argument for positionals`. The `required` flag doesn't work for positionals in `argparse` since they're already assumed to be inputted. I make the `experiment` argument optional by using `nargs` (which I now realize should be limited to 1 argument so that will be changed!)

2021-11-19 19:16 UTC, slimnsour commented on bin/dm_xnat_extract.py
> +    --use-dcm2bids           Pull xnat data and convert to bids using dcm2bids
Good catch, the usage argments docstring was removed in c130ceeb5704aa3854f29b7ed461d167555a6744

2021-11-19 19:16 UTC, slimnsour commented on bin/dm_xnat_extract.py
> +from pathlib import Path
Good point, I switched it to only use `os.path` in c130ceeb5704aa3854f29b7ed461d167555a6744

2021-11-19 19:19 UTC, slimnsour commented on bin/dm_xnat_extract.py
> +        help="Pull xnat data and convert to bids using dcm2bids"
I moved it to the main group cause it makes more sense there like you said, but Im not sure how to only expose dcm2bids arguments when we read from the parser with `argparse`. Reading from a specific group is not supported and subparsers would break the usage I mentioned in https://github.com/TIGRLab/datman/pull/317#issuecomment-974262017

2021-11-19 19:33 UTC, josephmje commented on bin/dm_xnat_extract.py
> +        action="store",
My mistake!

2021-11-19 19:49 UTC, jerdra commented on bin/dm_xnat_extract.py
> +        help="Pull xnat data and convert to bids using dcm2bids"
i think @josephmje wants to warn/prevent users from using BIDS related flags when --use-dcm2bids isn't selected. What we could do is to add a bit of code after parsing to check if any of the BIDS config exists when --dcm2bids *is not selected* and either:
1. Throw up a warning indicated that those args will be ignored
2. Use `ArgumentParser.error` with a message
3. 
I prefer option 2 personally as it'll prevent mistakes from running through

2021-11-19 20:37 UTC, josephmje commented on bin/dm_xnat_extract.py
> +        help="Pull xnat data and convert to bids using dcm2bids"
Yup! Could do something like

```
if not args.use_dcm2bids and (args.bids_out or args.dcm_config or ...):
    parser.error("dcm2bids configuration required --use-dcm2bids")
```

2021-11-19 21:49 UTC, slimnsour commented on bin/dm_xnat_extract.py
> +        help="Pull xnat data and convert to bids using dcm2bids"
Ah gotcha, thank you guys for laying that out! I added it in b1cb96bb5d86be38a4ca608afbec8ca4b629b15a

2021-11-22 14:03 UTC, jerdra approved these changes
Good work and thanks for incorporating our feedback @slimnsour!

2021-11-22 16:33 UTC, josephmje approved these changes

2021-11-30 17:39 UTC, merged